// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qghxfzkzcafrgifgvemq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnaHhmemt6Y2FmcmdpZmd2ZW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjc0MTQsImV4cCI6MjA2MTY0MzQxNH0.eSoHfEc8Jml-BqOwTwhO27nSKf6OhJTeHfxRPPXf8lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);